const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  REMOVE_ITEM: 'REMOVE_ITEM',
  ADD_ITEM: 'ADD_ITEM',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  CLEAR_ALL_ITEM_FROM_CART: 'CLEAR_ALL_ITEM_FROM_CART',
  TOGGLE_FAVORITE: 'TOGGLE_FAVORITE',
  REMOVE_FAVORITE: ' REMOVE_FAVORITE',
};

export default CartActionTypes;
